apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ame6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/bgriggs-tenant/devfile-sample/devfile-sample-ame6@sha256:bca57cf7b14d6a9707a239b43399a8a71c45832547f62fba34bce48bb58eb2cf
        name: my-nodejs
        resources: {}
status: {}
