apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ame6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ame6
    app.kubernetes.io/part-of: devfile-sample
  name: devfile-sample-ame6ot3r
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-ame6
    weight: null
status: {}
